name: Test Suite
on: [push]
jobs:
  ubuntu-gcc:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Get CMake
        uses: lukka/get-cmake@latest
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          workflowPreset: 'ubuntu-gcc'
  ubuntu-clang:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Get CMake
        uses: lukka/get-cmake@latest
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          workflowPreset: 'ubuntu-clang'
  windows-msvc:
    runs-on: windows-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Get CMake
        uses: lukka/get-cmake@latest
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          workflowPreset: 'windows-msvc'
  windows-msvc-clang:
    runs-on: windows-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Get CMake
        uses: lukka/get-cmake@latest
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          workflowPreset: 'windows-msvc-clang'
  windows-clang:
    runs-on: windows-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Get CMake
        uses: lukka/get-cmake@latest
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'windows-clang'
  # macos-arm64:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Git checkout
  #       uses: actions/checkout@v4
  #     - name: Get CMake
  #       uses: lukka/get-cmake@latest
  #     - name: Run CMake
  #       uses: lukka/run-cmake@v10
  #       with:
  #         workflowPreset: 'macos'
  # macos-x64:
  #   runs-on: macos-13
  #   steps:
  #     - name: Git checkout
  #       uses: actions/checkout@v4
  #     - name: Get CMake
  #       uses: lukka/get-cmake@latest
  #     - name: Run CMake
  #       uses: lukka/run-cmake@v10
  #       with:
  #         workflowPreset: 'macos'
