name: Test Suite
on: [push]
jobs:
  ubuntu-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.25.0"
      - run: cmake --workflow --preset ubuntu-gcc
  ubuntu-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.25.0"
      - run: sudo apt-get install clang
      - run: cmake --workflow --preset ubuntu-clang
  windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.25.0"
      - run: cmake --workflow --preset windows-msvc
  windows-msvc-clang:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.25.0"
      - run: cmake --workflow --preset windows-msvc-clang
  windows-clang:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.25.0"
      - run: cmake --workflow --preset windows-clang
